config/routes.rb
Rrs::Application.routes.draw do
  root 'homes#index'
  
  resources :contacts
  get "/contacts" => "contacts#index"

  resources :documents
  get "/docs" => "documents#index"

  resources :media
  get "/media" => "media#index"

  resources :outreaches
  get "/outreach" => "outreaches#index"

  resources :projects
  get "/projects" => "projects#index"

  resources :news
  get "/news" => "news#index"

  resources :homes
  
    
  devise_for :users

  

end

app/models/outreach.rb
class Outreach < ActiveRecord::Base
end

app/controllers/outreaches_controller.rb
class OutreachesController < ApplicationController
  before_action :set_outreach, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /outreaches
  # GET /outreaches.json
  def index
    @outreaches = Outreach.all.reverse
  end

  # GET /outreaches/1
  # GET /outreaches/1.json
  def show
  end

  # GET /outreaches/new
  def new
    @outreach = Outreach.new
  end

  # GET /outreaches/1/edit
  def edit
  end

  # POST /outreaches
  # POST /outreaches.json
  def create
    @outreach = Outreach.new(outreach_params)

    respond_to do |format|
      if @outreach.save
        format.html { redirect_to @outreach, notice: 'Outreach was successfully created.' }
        format.json { render action: 'show', status: :created, location: @outreach }
      else
        format.html { render action: 'new' }
        format.json { render json: @outreach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outreaches/1
  # PATCH/PUT /outreaches/1.json
  def update
    respond_to do |format|
      if @outreach.update(outreach_params)
        format.html { redirect_to @outreach, notice: 'Outreach was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @outreach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outreaches/1
  # DELETE /outreaches/1.json
  def destroy
    @outreach.destroy
    respond_to do |format|
      format.html { redirect_to outreaches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outreach
      @outreach = Outreach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outreach_params
      params.require(:outreach).permit(:content, :title)
    end
end

app/helpers/outreaches_helper.rb
module OutreachesHelper
end

app/views/outreaches/_form.html.erb
<%= form_for(@outreach) do |f| %>
  <% if @outreach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outreach.errors.count, "error") %> prohibited this outreach from being saved:</h2>

      <ul>
      <% @outreach.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field" >
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => 'ckeditor' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outreaches/edit.html.erb
<h1>Editing outreach</h1>

<%= render 'form' %>

<%= link_to 'Show', @outreach %> |
<%= link_to 'Back', outreaches_path %>

app/views/outreaches/index.html.erb
<% content_for :j do %>
<script type="text/javascript">
	$(document).ready(function(){
	    $('#out').addClass('active');
	});
</script>
<% end %>

<% if user_signed_in? %>
<% if current_user.admin? %>
<div data-no-turbolink>
	<%= link_to("New Outreach Event", new_outreach_path) %>
</div>
<% end %>
<% end %>


<% if @outreaches.count == 0 %>
  <p style = "text-align:center;">No outreach events now, come back later.</p>
<% else %>
  <% count = 0 %>
  <% @outreaches.each do |n| %>
  	<% if count < 1 %>
      <div>
        <h2><%= n.title %></h2>
        <div style = "margin-left: 50px;">
        <%=raw n.content %>
      </div>
    </div>
    <% count = count + 1 %> 
  <% else %> 
    <div style = "border-top: 1px dashed grey;">
      <h2><%= n.title %></h2>
      <div style = "margin-left: 50px;">
        <%=raw n.content %>
      </div>
    </div>
  <% end %>
  <% end %>
<% end %>

app/views/outreaches/new.html.erb
<h1>New outreach</h1>

<%= render 'form' %>

<%= link_to 'Back', outreaches_path %>

app/views/outreaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @outreach.content %>
</p>

<%= link_to 'Edit', edit_outreach_path(@outreach) %> |
<%= link_to 'Back', outreaches_path %>