config/routes.rb
Rrs::Application.routes.draw do
  root 'homes#index'
  
  resources :contacts
  get "/contacts" => "contacts#index"

  resources :documents
  get "/docs" => "documents#index"

  resources :media
  get "/media" => "media#index"

  resources :outreaches
  get "/outreach" => "outreaches#index"

  resources :projects
  get "/projects" => "projects#index"

  resources :news
  get "/news" => "news#index"

  resources :homes
  
    
  devise_for :users

  

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /news
  # GET /news.json
  def index
    @news = News.all.reverse
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render action: 'show', status: :created, location: @news }
      else
        format.html { render action: 'new' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:content, :title)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field" >
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => 'ckeditor' %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<% content_for :j do %>
<script type="text/javascript">
	$(document).ready(function(){
	    $('#news').addClass('active');
	});
</script>
<% end %>

<% if user_signed_in? %>
<% if current_user.admin? %>
<div data-no-turbolink>
	<%= link_to("New News", new_news_path) %>
</div>
<% end %>
<% end %>


<% if @news.count == 0 %>
	<p style = "text-align:center;">No news now, come back later.</p>
<% else %>
	<% count = 0 %>
	<% @news.each do |n| %>
		<% if count < 1 %>
	  	<div>
	  		<h2><%= n.title %></h2>
		    <div style = "margin-left: 50px;">
				<%=raw n.content %>
			</div>
		</div>
		<% count = count + 1 %> 
	<% else %> 
		<div style = "border-top: 1px dashed grey;">
			<h2><%= n.title %></h2>
			<div style = "margin-left: 50px;">
				<%=raw n.content %>
			</div>
		</div>
	<% end %>
	<% end %>
<% end %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @news.content %>
</p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>