config/routes.rb
Rrs::Application.routes.draw do
  root 'homes#index'
  
  resources :contacts
  get "/contacts" => "contacts#index"

  resources :documents
  get "/docs" => "documents#index"

  resources :media
  get "/media" => "media#index"

  resources :outreaches
  get "/outreach" => "outreaches#index"

  resources :projects
  get "/projects" => "projects#index"

  resources :news
  get "/news" => "news#index"

  resources :homes
  
    
  devise_for :users

  

end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all.reverse
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :docUrl, :txtUrl)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :docUrl %><br>
    <%= f.text_field :docUrl %>
  </div>
  <div class="field">
    <%= f.label :txtUrl %><br>
    <%= f.text_field :txtUrl %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<% content_for :j do %>
<script type="text/javascript">
  $(document).ready(function(){
      $('#docs').addClass('active');
  });
</script>
<% end %>

<% if user_signed_in? %>
<% if current_user.admin? %>
  <%= link_to("New Document", new_document_path) %>
<% end %>
<% end %>

<% if @documents.count == 0 %>
  <p style = "text-align:center;">No documents now, come back later.</p>
<% else %>
  <% @documents.each do |n| %>
    <p><%= n.name %>: <a href="<%= n.docUrl %>">.doc</a>, <a href="<%= n.txtUrl %>">.txt</a></p>
  <% end %>
<% end %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>Docurl:</strong>
  <%= @document.docUrl %>
</p>

<p>
  <strong>Txturl:</strong>
  <%= @document.txtUrl %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>